# This is the configuration file for the Docker inventory script: docker_inventory.py.
#
# defaults: Defines a default connnection. Defaults will be taken from this and applied to any values not provided 
#           for a host defined in the hosts list.
#
# hosts: If you wish to get inventory from more than one Docker daemon hosts, define a hosts list.
# 
# For a host defined in defaults or hosts, you can provided the following attributes. The only required attribute is host.
#
#   host:
#       description: The URL or Unix socket path for the host. 
#       required: yes
#   tls:
#      description: Connect using https://
#      default: false
#      required: false
#   tls_verify:
#      description: Connect using https:// and verify the host name matches the host name found in the certificate.
#      default: false
#      required: false
#   cert_path:
#      description: Path to the client's certificate .pem file.
#      default: null
#      required: false
#   cacert_path:
#      description: Path to the client's Certificate Authority .pem file.
#      default: null
#      required: false
#   key_path:
#      description: Path to the client's encryption key .pem file
#      default: null
#      required: false
#   version:
#      description: The API version the client will use.
#      required: false
#      default: will be supplied by the docker-py module.
#   timeout:
#      description: The amount of time in seconds to wait on an API response. 
#      required: false
#      default: will be supplied by the docker-py module.
#   default_ip:
#      description: The IP address to assign to ansilbe_host when the container's SSH port is mappped to 0.0.0.0
#      required: false
#      default: 1267.0.0.1
#   private_ssh_port:
#      description: The port containers use for SSH
#      required: false
#      default: 22
#   

#defaults:
#  host: unix:///var/run/docker.sock
#  private_ssh_port: 22
#  default_ip: 127.0.0.1

#hosts:
#  - host: tcp://10.45.5.16:4243
#    private_ssh_port: 2022
#    default_ip: 172.16.3.45
#  - host: tcp://localhost:4243
#    private_ssh_port: 2029
